version: "3"
    
services:
  app:
    image: rag-chat-storage-app:11
    container_name: rag-chat-storage-app
    build:
      context: .           
      dockerfile: Dockerfile
    ports:
      - "8081:8081"     
    env_file:
      - .env
    restart: always       
    depends_on:
      - database
      - logstash
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.6
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      - pipeline.ecs_compatibility=disabled
    depends_on:
      - elasticsearch
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    container_name: kibana
    ports:
      - "5601:5601"
    env_file:
      - .env 
    depends_on:
      - elasticsearch
      - logstash

  database:
    image: postgres:15
    container_name: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - database
    
