server:
  port: ${SERVICE_PORT:8081}

spring:
  datasource:
# postgresql connection settings
    url: ${DATASOUCE_URL:jdbc:postgresql://localhost:5432/ragchat}
    username: ${DATASOUCE_USER_NAME:test}
    password: ${DATASOUCE_PASSWORD:test}

#ratelimit settings
ratelimit:
  configs:
    limit-for-period: ${RATE_LIMIT_COUNT:5} 
    limit-refresh-period: ${RATE_LIMIT_REFRESH_PERIOD:1} 
    timeout-duration: ${RATE_LIMIT_TIMEOUT:0}

#Cors settings
cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:'*'}
    
#security auth users
security:
  api-keys: ${APP_API_KEYS:fb939c58-6721-43d4-a521-7079d5ba6a7a,576c5d84-fcab-44d4-858a-cd17f64aa085}
    
logstash:
  connection: ${LOGSTASH_SERVER:localhost:5000}