server:
  port: 8081

spring:
  datasource:
# postgresql connection settings
    url: jdbc:postgresql://localhost:5432/ragchat
    username: test
    password: test
    
#ratelimit settings
ratelimit:
  configs:
    limit-for-period: 5
    limit-refresh-period: 1
    timeout-duration: 0 

#Cors settings
cors:
  allowed:
    origin: '*'
    
#security auth users
security:
  api-keys: fb939c58-6721-43d4-a521-7079d5ba6a7a:user-01, 576c5d84-fcab-44d4-858a-cd17f64aa085:user-02
    

